// i18n Language Configuration for CFBlog Admin
// 国际化语言配置

type StorageLike = {
  getItem(key: string): string | null;
  setItem(key: string, value: string): void;
};

export type Language = 'zh' | 'en';

function getLocalStorage(): StorageLike | undefined {
  return (globalThis as typeof globalThis & { localStorage?: StorageLike }).localStorage;
}

export const i18n = {
  // 当前语言
  currentLang: 'zh' as Language, // 默认中文

  // 获取翻译文本
  t(key: string): string {
    const keys = key.split('.');
    let value: unknown = this.translations[this.currentLang];

    for (const k of keys) {
      if (value && typeof value === 'object' && k in value) {
        value = (value as Record<string, unknown>)[k];
      } else {
        return key; // 如果找不到翻译，返回key本身
      }
    }

    return typeof value === 'string' ? value : key;
  },

  // 切换语言
  setLang(lang: Language) {
    this.currentLang = lang;
    getLocalStorage()?.setItem('admin_lang', lang);
  },

  // 初始化语言
  initLang() {
    const savedLang = getLocalStorage()?.getItem('admin_lang');
    if (savedLang === 'zh' || savedLang === 'en') {
      this.currentLang = savedLang;
    }
  },

  // 翻译对照表
  translations: {
    zh: {
      // 导航菜单
      nav: {
        dashboard: '仪表盘',
        posts: '文章',
        pages: '页面',
        moments: '动态',
        categories: '分类',
        tags: '标签',
        media: '媒体库',
        links: '友情链接',
        comments: '评论',
        users: '用户',
        settings: '设置',
        logout: '退出登录'
      },

      // 通用
      common: {
        add: '添加',
        edit: '编辑',
        delete: '删除',
        create: '创建',
        update: '更新',
        save: '保存',
        cancel: '取消',
        close: '关闭',
        view: '查看',
        upload: '上传',
        insert: '插入',
        search: '搜索',
        filter: '筛选',
        all: '全部',
        yes: '是',
        no: '否',
        actions: '操作',
        status: '状态',
        date: '日期',
        name: '名称',
        slug: '别名',
        description: '描述',
        count: '数量',
        required: '必填',
        optional: '可选'
      },

      // 文章
      posts: {
        title: '文章',
        allPosts: '所有文章',
        addNew: '添加文章',
        createNew: '创建新文章',
        editPost: '编辑文章',
        postTitle: '标题',
        content: '内容',
        excerpt: '摘要',
        featuredImage: '特色图片',
        sticky: '置顶',
        publishDate: '发布日期',
        categories: '分类',
        tags: '标签',
        author: '作者',
        noPostsYet: '还没有文章。创建你的第一篇文章！',
        createPost: '创建文章',
        updatePost: '更新文章',
        deleteConfirm: '确定要删除这篇文章吗？',
        addMedia: '添加媒体',
        selectFromLibrary: '从媒体库选择',
        autoGenerated: '留空自动生成',
        customDate: '可以自定义文章发布日期',
        createNewTag: '创建新标签',
        addNewTag: '添加新标签'
      },

      // 状态
      statusOptions: {
        draft: '草稿',
        publish: '发布',
        published: '已发布',
        private: '私密',
        pending: '待审核',
        approved: '已批准',
        spam: '垃圾',
        trash: '回收站',
        open: '开启',
        closed: '关闭'
      },

      // 分类
      categories: {
        title: '分类',
        allCategories: '所有分类',
        addNew: '添加分类',
        createNew: '创建新分类',
        editCategory: '编辑分类',
        categoryName: '分类名称',
        parentCategory: '父分类',
        none: '无',
        noCategories: '还没有分类。',
        createCategory: '创建分类',
        updateCategory: '更新分类',
        deleteConfirm: '确定要删除这个分类吗？'
      },

      // 标签
      tags: {
        title: '标签',
        allTags: '所有标签',
        addNew: '添加标签',
        createNew: '创建新标签',
        editTag: '编辑标签',
        tagName: '标签名称',
        noTags: '还没有标签。',
        createTag: '创建标签',
        updateTag: '更新标签',
        deleteConfirm: '确定要删除这个标签吗？'
      },

      // 媒体库
      media: {
        title: '媒体库',
        uploadFiles: '上传文件',
        uploadNew: '上传新媒体',
        selectFile: '选择文件',
        fileName: '文件名',
        fileType: '文件类型',
        fileSize: '文件大小',
        uploadedDate: '上传日期',
        altText: '替代文本',
        noMedia: '未找到媒体文件。',
        uploadMedia: '上传媒体'
      },

      // 用户
      users: {
        title: '用户',
        allUsers: '所有用户',
        addNew: '添加用户',
        createNew: '创建新用户',
        editUser: '编辑用户',
        username: '用户名',
        email: '邮箱',
        displayName: '显示名称',
        password: '密码',
        role: '角色',
        bio: '简介',
        registered: '注册时间',
        noUsers: '未找到用户。',
        createUser: '创建用户',
        updateUser: '更新用户',
        deleteConfirm: '确定要删除这个用户吗？'
      },

      // 角色
      roles: {
        administrator: '管理员',
        editor: '编辑',
        author: '作者',
        contributor: '贡献者',
        subscriber: '订阅者'
      },

      // 页面
      pages: {
        title: '页面',
        allPages: '所有页面',
        addNew: '添加页面',
        createNew: '创建新页面',
        editPage: '编辑页面',
        noPages: '还没有页面。',
        createPage: '创建页面',
        updatePage: '更新页面',
        deleteConfirm: '确定要删除这个页面吗？',
        commentStatus: '评论状态'
      },

      // 动态
      moments: {
        title: '动态',
        allMoments: '所有动态',
        addNew: '添加动态',
        createNew: '创建新动态',
        editMoment: '编辑动态',
        momentContent: '动态内容',
        mediaUrls: '媒体 URL',
        noMoments: '还没有动态。',
        createMoment: '创建动态',
        updateMoment: '更新动态',
        deleteConfirm: '确定要删除这条动态吗？',
        whatOnMind: '分享你的想法...'
      },

      // 评论
      comments: {
        title: '评论',
        allComments: '所有评论',
        author: '作者',
        comment: '评论',
        post: '文章',
        noComments: '未找到评论。',
        ownerBadge: '博主',
        approve: '批准',
        markAsSpam: '标记为垃圾',
        reply: '回复',
        replyTo: '回复评论',
        replyContent: '回复内容',
        sendReply: '发送回复',
        editComment: '编辑评论',
        deleteConfirm: '确定要删除这条评论吗？'
      },

      // 友情链接
      links: {
        title: '友情链接',
        allLinks: '所有链接',
        addNew: '添加链接',
        createNew: '创建新链接',
        editLink: '编辑链接',
        siteName: '网站名称',
        siteUrl: '网站地址',
        linkDescription: '链接描述',
        avatarUrl: '头像 URL',
        linkCategory: '链接分类',
        target: '打开方式',
        visible: '可见',
        sortOrder: '排序',
        noLinks: '还没有链接。',
        createLink: '创建链接',
        updateLink: '更新链接',
        deleteConfirm: '确定要删除这个链接吗？',
        manageCategories: '管理分类',
        lowerFirst: '数字越小排序越靠前'
      },

      // 设置
      settings: {
        title: '网站设置',
        language: '界面语言',
        languageHint: '选择后台管理界面的显示语言',
        siteTitle: '网站标题',
        siteTitleHint: '将显示在浏览器标题栏和站点页头中。',
        siteUrl: '网站地址',
        siteUrlHint: '填写站点完整 URL，不要包含末尾斜杠。它也会作为 WordPress API 的 home URL。',
        adminEmail: '管理员邮箱',
        adminEmailHint: '该邮箱将用于接收后台通知。',
        emailNotifications: '邮件通知',
        fromName: '发件人名称',
        fromNameHint: '通知邮件中显示的发件人名称。',
        fromEmail: '发件邮箱',
        fromEmailHint: '请填写已在 Resend 中验证域名下的发件地址。',
        enableMailNotifications: '启用邮件通知',
        enableMailNotificationsHint: '需要先在 Worker 中配置 <code>RESEND_API_KEY</code> Secret。',
        notifyAdminOnComment: '有新评论时通知管理员',
        notifyCommenterOnReply: '有人回复评论时通知原评论者',
        siteDescription: '网站描述',
        siteDescriptionHint: '用于 SEO 描述信息。',
        homePostsPerPage: '首页文章列表数量',
        homePostsPerPageHint: '控制首页和搜索结果页每页显示的文章数，建议 1-100。',
        siteKeywords: '网站关键词',
        siteKeywordsHint: '使用逗号分隔多个关键词，用于 SEO。',
        siteAuthor: '网站作者',
        siteFavicon: '网站图标',
        siteFaviconHint: '网站 favicon 地址，推荐 32x32。',
        siteLogo: '网站Logo',
        siteLogoHint: '网站 Logo 图片地址。',
        siteNotice: '网站公告',
        siteNoticeHint: '显示在前台侧边栏公告卡片中，支持多行文本。',
        siteNoticePlaceholder: '每行一段公告内容',
        siteIcp: 'ICP备案号',
        siteIcpHint: '仅中国大陆站点需要填写。',
        siteIcpPlaceholder: '京ICP备xxxxx号',
        footerText: '页脚文本',
        footerTextHint: '显示在每个页面底部，支持 HTML。',
        headHtml: '自定义 Head HTML',
        headHtmlHint: '将插入到站点 <head> 中，可用于分析脚本、自定义 CSS 或 meta 标签。',
        socialContacts: '社交联系方式',
        email: '邮箱',
        socialTelegramPlaceholder: '@username 或 https://t.me/username',
        socialXPlaceholder: '@username 或 https://x.com/username',
        socialMastodonPlaceholder: '完整主页地址',
        socialQqPlaceholder: 'QQ号码',
        webhookSection: 'Webhook 设置',
        webhookUrl: 'Webhook地址',
        webhookUrlHint: 'Webhook 事件推送地址，留空则关闭 Webhook。',
        webhookSecret: 'Webhook密钥',
        webhookSecretHint: '用于 HMAC-SHA256 签名，签名会通过 <code>X-Webhook-Signature</code> 请求头发送。',
        webhookSecretPlaceholder: '请输入密钥',
        webhookEvents: 'Webhook事件',
        webhookEventsSelect: '选择要触发 Webhook 的事件：',
        webhookEventPostCreated: '文章创建为草稿',
        webhookEventPostUpdated: '文章更新',
        webhookEventPostPublished: '文章发布',
        webhookEventPostDeleted: '文章删除',
        webhookEventCommentCreated: '评论创建',
        webhookEventCommentUpdated: '评论更新',
        webhookEventCommentDeleted: '评论删除',
        webhookEventsHint: '选择哪些事件会触发 Webhook。全部不勾选则不发送。',
        webhookRecommended: '部署推荐：',
        webhookTipsTitle: 'Webhook 提示：',
        webhookTipDeploy: '对于 Vercel/Cloudflare Pages 部署：建议只勾选 post.published 和 post.updated，避免不必要的构建。',
        webhookTipPublish: '创建并发布文章：只会触发 post.published，避免重复。',
        webhookTipDraft: '保存草稿：触发 post.created。',
        webhookTipDraftToPublish: '草稿发布：触发 post.published。',
        webhookTipUpdatePublished: '更新已发布文章：触发 post.updated。',
        saveSettings: '保存设置',
        settingsSaved: '设置已保存！',
        saveFailed: '保存设置失败：',
        loadFailed: '加载设置失败。'
      },

      // 仪表盘
      dashboard: {
        welcome: '欢迎来到',
        subtitle: '基于 Cloudflare Workers、D1 和 R2 的 WordPress 风格无头博客',
        stats: {
          posts: '文章',
          pages: '页面',
          comments: '评论',
          categories: '分类',
          tags: '标签',
          media: '媒体',
          links: '链接',
          users: '用户',
          moments: '动态'
        }
      },

      // 消息提示
      messages: {
        loading: '加载中...',
        saving: '保存中...',
        saved: '已保存',
        created: '创建成功！',
        updated: '更新成功！',
        deleted: '删除成功！',
        uploaded: '上传成功！',
        failed: '操作失败',
        error: '发生错误',
        confirm: '确认',
        cancel: '取消'
      }
    },

    en: {
      // Navigation
      nav: {
        dashboard: 'Dashboard',
        posts: 'Posts',
        pages: 'Pages',
        moments: 'Moments',
        categories: 'Categories',
        tags: 'Tags',
        media: 'Media',
        links: 'Links',
        comments: 'Comments',
        users: 'Users',
        settings: 'Settings',
        logout: 'Logout'
      },

      // Common
      common: {
        add: 'Add',
        edit: 'Edit',
        delete: 'Delete',
        create: 'Create',
        update: 'Update',
        save: 'Save',
        cancel: 'Cancel',
        close: 'Close',
        view: 'View',
        upload: 'Upload',
        insert: 'Insert',
        search: 'Search',
        filter: 'Filter',
        all: 'All',
        yes: 'Yes',
        no: 'No',
        actions: 'Actions',
        status: 'Status',
        date: 'Date',
        name: 'Name',
        slug: 'Slug',
        description: 'Description',
        count: 'Count',
        required: 'Required',
        optional: 'Optional'
      },

      // Posts
      posts: {
        title: 'Posts',
        allPosts: 'All Posts',
        addNew: 'Add New',
        createNew: 'Create New Post',
        editPost: 'Edit Post',
        postTitle: 'Title',
        content: 'Content',
        excerpt: 'Excerpt',
        featuredImage: 'Featured Image',
        sticky: 'Sticky',
        publishDate: 'Publish Date',
        categories: 'Categories',
        tags: 'Tags',
        author: 'Author',
        noPostsYet: 'No posts yet. Create your first post!',
        createPost: 'Create Post',
        updatePost: 'Update Post',
        deleteConfirm: 'Are you sure you want to delete this post?',
        addMedia: 'Add Media',
        selectFromLibrary: 'Select from Library',
        autoGenerated: 'Leave empty for auto-generation',
        customDate: 'Custom publish date',
        createNewTag: 'Create new tag',
        addNewTag: 'Add New Tag'
      },

      // Status Options
      statusOptions: {
        draft: 'Draft',
        publish: 'Publish',
        published: 'Published',
        private: 'Private',
        pending: 'Pending',
        approved: 'Approved',
        spam: 'Spam',
        trash: 'Trash',
        open: 'Open',
        closed: 'Closed'
      },

      // Categories
      categories: {
        title: 'Categories',
        allCategories: 'All Categories',
        addNew: 'Add New',
        createNew: 'Create New Category',
        editCategory: 'Edit Category',
        categoryName: 'Category Name',
        parentCategory: 'Parent Category',
        none: 'None',
        noCategories: 'No categories yet.',
        createCategory: 'Create Category',
        updateCategory: 'Update Category',
        deleteConfirm: 'Are you sure you want to delete this category?'
      },

      // Tags
      tags: {
        title: 'Tags',
        allTags: 'All Tags',
        addNew: 'Add New',
        createNew: 'Create New Tag',
        editTag: 'Edit Tag',
        tagName: 'Tag Name',
        noTags: 'No tags yet.',
        createTag: 'Create Tag',
        updateTag: 'Update Tag',
        deleteConfirm: 'Are you sure you want to delete this tag?'
      },

      // Media
      media: {
        title: 'Media Library',
        uploadFiles: 'Upload Files',
        uploadNew: 'Upload New Media',
        selectFile: 'Select File',
        fileName: 'File Name',
        fileType: 'File Type',
        fileSize: 'File Size',
        uploadedDate: 'Uploaded Date',
        altText: 'Alt Text',
        noMedia: 'No media found.',
        uploadMedia: 'Upload Media'
      },

      // Users
      users: {
        title: 'Users',
        allUsers: 'All Users',
        addNew: 'Add New',
        createNew: 'Create New User',
        editUser: 'Edit User',
        username: 'Username',
        email: 'Email',
        displayName: 'Display Name',
        password: 'Password',
        role: 'Role',
        bio: 'Bio',
        registered: 'Registered',
        noUsers: 'No users found.',
        createUser: 'Create User',
        updateUser: 'Update User',
        deleteConfirm: 'Are you sure you want to delete this user?'
      },

      // Roles
      roles: {
        administrator: 'Administrator',
        editor: 'Editor',
        author: 'Author',
        contributor: 'Contributor',
        subscriber: 'Subscriber'
      },

      // Pages
      pages: {
        title: 'Pages',
        allPages: 'All Pages',
        addNew: 'Add New',
        createNew: 'Create New Page',
        editPage: 'Edit Page',
        noPages: 'No pages yet.',
        createPage: 'Create Page',
        updatePage: 'Update Page',
        deleteConfirm: 'Are you sure you want to delete this page?',
        commentStatus: 'Comment Status'
      },

      // Moments
      moments: {
        title: 'Moments',
        allMoments: 'All Moments',
        addNew: 'Add New',
        createNew: 'Create New Moment',
        editMoment: 'Edit Moment',
        momentContent: 'Moment Content',
        mediaUrls: 'Media URLs',
        noMoments: 'No moments yet.',
        createMoment: 'Create Moment',
        updateMoment: 'Update Moment',
        deleteConfirm: 'Are you sure you want to delete this moment?',
        whatOnMind: "What's on your mind?"
      },

      // Comments
      comments: {
        title: 'Comments',
        allComments: 'All Comments',
        author: 'Author',
        comment: 'Comment',
        post: 'Post',
        noComments: 'No comments found.',
        ownerBadge: 'Author',
        approve: 'Approve',
        markAsSpam: 'Mark as Spam',
        reply: 'Reply',
        replyTo: 'Reply to Comment',
        replyContent: 'Reply Content',
        sendReply: 'Send Reply',
        editComment: 'Edit Comment',
        deleteConfirm: 'Are you sure you want to delete this comment?'
      },

      // Links
      links: {
        title: 'Links',
        allLinks: 'All Links',
        addNew: 'Add New',
        createNew: 'Create New Link',
        editLink: 'Edit Link',
        siteName: 'Site Name',
        siteUrl: 'Site URL',
        linkDescription: 'Link Description',
        avatarUrl: 'Avatar URL',
        linkCategory: 'Link Category',
        target: 'Target',
        visible: 'Visible',
        sortOrder: 'Sort Order',
        noLinks: 'No links yet.',
        createLink: 'Create Link',
        updateLink: 'Update Link',
        deleteConfirm: 'Are you sure you want to delete this link?',
        manageCategories: 'Manage Categories',
        lowerFirst: 'Lower numbers appear first'
      },

      // Settings
      settings: {
        title: 'Site Settings',
        language: 'Interface Language',
        languageHint: 'Choose the display language for admin interface',
        siteTitle: 'Site Title',
        siteTitleHint: 'This will be displayed in the browser title bar and site header.',
        siteUrl: 'Site URL',
        siteUrlHint: 'Enter the full site URL without a trailing slash. It is also used as the home URL in the WordPress API.',
        adminEmail: 'Admin Email',
        adminEmailHint: 'This email will be used for administrative notifications.',
        emailNotifications: 'Email Notifications',
        fromName: 'From Name',
        fromNameHint: 'The sender name shown in notification emails.',
        fromEmail: 'From Email',
        fromEmailHint: 'Use a sender address from a domain that has already been verified in Resend.',
        enableMailNotifications: 'Enable email notifications',
        enableMailNotificationsHint: 'Requires the <code>RESEND_API_KEY</code> Worker secret to be configured.',
        notifyAdminOnComment: 'Notify admin when a new comment is submitted',
        notifyCommenterOnReply: 'Notify the original commenter when someone replies',
            siteDescription: 'Site Description',
            siteDescriptionHint: 'Used for the SEO meta description.',
            homePostsPerPage: 'Homepage post count',
            homePostsPerPageHint: 'Controls how many posts appear per page on the homepage and search results. Recommended: 1-100.',
            siteKeywords: 'Site Keywords',
            siteKeywordsHint: 'Comma-separated keywords for SEO.',
        siteAuthor: 'Site Author',
        siteFavicon: 'Site Favicon',
        siteFaviconHint: 'URL to your site favicon. Recommended: 32x32.',
        siteLogo: 'Site Logo',
        siteLogoHint: 'URL to your site logo image.',
        siteNotice: 'Site Notice',
        siteNoticeHint: 'Displayed in the public site notice card and supports multiple lines.',
        siteNoticePlaceholder: 'One notice per line',
        siteIcp: 'ICP Number',
        siteIcpHint: 'Only needed for websites in mainland China.',
        siteIcpPlaceholder: 'ICP filing number',
        footerText: 'Footer Text',
        footerTextHint: 'Displayed at the bottom of every page. HTML is supported.',
        headHtml: 'Custom Head HTML',
        headHtmlHint: 'Inserted into the site <head>. Useful for analytics, custom CSS, or meta tags.',
        socialContacts: 'Social Contacts',
        email: 'Email',
        socialTelegramPlaceholder: '@username or https://t.me/username',
        socialXPlaceholder: '@username or https://x.com/username',
        socialMastodonPlaceholder: 'Full profile URL',
        socialQqPlaceholder: 'QQ number',
        webhookSection: 'Webhook Settings',
        webhookUrl: 'Webhook URL',
        webhookUrlHint: 'Webhook delivery URL. Leave empty to disable webhooks.',
        webhookSecret: 'Webhook Secret',
        webhookSecretHint: 'Used to sign payloads with HMAC-SHA256. The signature is sent in the <code>X-Webhook-Signature</code> header.',
        webhookSecretPlaceholder: 'Enter a secret key',
        webhookEvents: 'Webhook Events',
        webhookEventsSelect: 'Select events to trigger webhook:',
        webhookEventPostCreated: 'Post saved as draft',
        webhookEventPostUpdated: 'Post updated',
        webhookEventPostPublished: 'Post published',
        webhookEventPostDeleted: 'Post deleted',
        webhookEventCommentCreated: 'Comment created',
        webhookEventCommentUpdated: 'Comment updated',
        webhookEventCommentDeleted: 'Comment deleted',
        webhookEventsHint: 'Choose which events should trigger the webhook. Leave all unchecked to disable webhooks.',
        webhookRecommended: 'Recommended for deployment:',
        webhookTipsTitle: 'Webhook Tips:',
        webhookTipDeploy: 'For Vercel/Cloudflare Pages deployment, only select post.published and post.updated to avoid unnecessary builds.',
        webhookTipPublish: 'Creating and publishing a post only triggers post.published, which avoids duplicates.',
        webhookTipDraft: 'Saving as draft triggers post.created.',
        webhookTipDraftToPublish: 'Publishing a draft triggers post.published.',
        webhookTipUpdatePublished: 'Updating a published post triggers post.updated.',
        saveSettings: 'Save Settings',
        settingsSaved: 'Settings saved!',
        saveFailed: 'Failed to save settings:',
        loadFailed: 'Failed to load settings.'
      },

      // Dashboard
      dashboard: {
        welcome: 'Welcome to',
        subtitle: 'Your WordPress-like headless blog powered by Cloudflare Workers, D1, and R2',
        stats: {
          posts: 'Posts',
          pages: 'Pages',
          comments: 'Comments',
          categories: 'Categories',
          tags: 'Tags',
          media: 'Media',
          links: 'Links',
          users: 'Users',
          moments: 'Moments'
        }
      },

      // Messages
      messages: {
        loading: 'Loading...',
        saving: 'Saving...',
        saved: 'Saved',
        created: 'Created successfully!',
        updated: 'Updated successfully!',
        deleted: 'Deleted successfully!',
        uploaded: 'Uploaded successfully!',
        failed: 'Operation failed',
        error: 'An error occurred',
        confirm: 'Confirm',
        cancel: 'Cancel'
      }
    }
  }
};

// 导出类型
export type TranslationKey = string;
